# Generated by Django 5.2.1 on 2026-01-12 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetfast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='modelo',
        ),
        migrations.CreateModel(
            name='ModeloVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='jetfast.marca')),
            ],
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo_veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jetfast.modeloveiculo'),
        ),
    ]
