# Generated by Django 5.2.1 on 2026-01-12 17:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetfast', '0002_marca_remove_veiculo_marca_remove_veiculo_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='modelo_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jetfast.modeloveiculo', verbose_name='Veículo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='A placa deve estar no formato ABC-1234 ou ABC1D23', regex='^[A-Z]{3}-?\\d[A-Z0-9]\\d{2}$')]),
        ),
    ]
