# Generated by Django 5.2.1 on 2026-01-20 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetfast', '0003_alter_veiculo_modelo_veiculo_alter_veiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavagem',
            name='data_lavagem',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
