# Generated by Django 5.2.1 on 2026-01-24 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetfast', '0004_alter_lavagem_data_lavagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='telefone',
            field=models.CharField(blank=True, help_text='Ex: (11) 99999-9999', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve estar no formato (11) 99999-9999 ou 11999999999', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
    ]
