# Generated by Django 5.2.1 on 2026-01-24 18:34

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetfast', '0005_veiculo_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lavagem',
            options={'ordering': ['-horario_chegada'], 'verbose_name_plural': 'Lavagens'},
        ),
        migrations.RemoveField(
            model_name='lavagem',
            name='data_lavagem',
        ),
        migrations.AddField(
            model_name='lavagem',
            name='horario_chegada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Chegada (Fila)'),
        ),
        migrations.AddField(
            model_name='lavagem',
            name='horario_pista',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início (Pista)'),
        ),
        migrations.AddField(
            model_name='lavagem',
            name='horario_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim (Saída)'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='telefone',
            field=models.CharField(blank=True, help_text='Ex: 11 99999-9999', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve estar no formato (11) 99999-9999 ou 11999999999', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
    ]
