# Generated by Django 5.2.1 on 2026-01-24 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetfast', '0006_alter_lavagem_options_remove_lavagem_data_lavagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.AddField(
            model_name='lavagem',
            name='colaborador_externa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lavagens_externas', to='jetfast.colaborador', verbose_name='Colaborador (Externa)'),
        ),
        migrations.AddField(
            model_name='lavagem',
            name='colaborador_interna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lavagens_internas', to='jetfast.colaborador', verbose_name='Colaborador (Interna)'),
        ),
    ]
