# Generated by Django 5.2.1 on 2026-01-25 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetfast', '0007_colaborador_lavagem_colaborador_externa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='plano',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jetfast.categoria', verbose_name='Categoria'),
        ),
        migrations.DeleteModel(
            name='Plano',
        ),
    ]
