# Generated by Django 5.2.1 on 2026-01-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetfast', '0008_categoria_remove_veiculo_plano_veiculo_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
