# Generated by Django 5.2.1 on 2026-01-26 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jetfast', '0009_colaborador_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'ordering': ['nome'], 'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
    ]
