# Generated by Django 6.0.1 on 2026-01-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetfast', '0010_alter_colaborador_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavagem',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
