# Generated by Django 6.0.1 on 2026-02-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetfast', '0011_lavagem_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='tipo_cliente',
            field=models.CharField(choices=[('JETFAST', 'JetFast'), ('ORGANICO', 'Orgânico')], default='ORGANICO', max_length=10, verbose_name='Tipo de Cliente'),
        ),
    ]
